# ga_lee
test_2.py만 작동. 
test.py와 test_1.py는 자료입력장소 에러! 
